import { Region } from "~~/components/shipping/shippingRates";

export type Country = {
  code: string;
  name: string;
  region: Region; 
};

export const supportedCountries: Country[] = [
  // ==========================================
  // REGION 0: NORTH AMERICA
  // ==========================================
  { code: "US", name: "United States of America", region: Region.NorthAmerica },
  { code: "CA", name: "Canada", region: Region.NorthAmerica },
  { code: "MX", name: "Mexico", region: Region.NorthAmerica },
  { code: "PR", name: "Puerto Rico", region: Region.NorthAmerica },
  { code: "AI", name: "Anguilla", region: Region.NorthAmerica },
  { code: "AG", name: "Antigua and Barbuda", region: Region.NorthAmerica },
  { code: "AW", name: "Aruba", region: Region.NorthAmerica },
  { code: "BS", name: "Bahamas", region: Region.NorthAmerica },
  { code: "BB", name: "Barbados", region: Region.NorthAmerica },
  { code: "BZ", name: "Belize", region: Region.NorthAmerica },
  { code: "BM", name: "Bermuda", region: Region.NorthAmerica },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", region: Region.NorthAmerica },
  { code: "KY", name: "Cayman Islands", region: Region.NorthAmerica },
  { code: "CR", name: "Costa Rica", region: Region.NorthAmerica },
  { code: "CU", name: "Cuba", region: Region.NorthAmerica },
  { code: "CW", name: "Curaçao", region: Region.NorthAmerica },
  { code: "DM", name: "Dominica", region: Region.NorthAmerica },
  { code: "DO", name: "Dominican Republic", region: Region.NorthAmerica },
  { code: "SV", name: "El Salvador", region: Region.NorthAmerica },
  { code: "GD", name: "Grenada", region: Region.NorthAmerica },
  { code: "GP", name: "Guadeloupe", region: Region.NorthAmerica },
  { code: "GT", name: "Guatemala", region: Region.NorthAmerica },
  { code: "HT", name: "Haiti", region: Region.NorthAmerica },
  { code: "HN", name: "Honduras", region: Region.NorthAmerica },
  { code: "JM", name: "Jamaica", region: Region.NorthAmerica },
  { code: "KN", name: "Saint Kitts and Nevis", region: Region.NorthAmerica },
  { code: "LC", name: "Saint Lucia", region: Region.NorthAmerica },
  { code: "MQ", name: "Martinique", region: Region.NorthAmerica },
  { code: "MS", name: "Montserrat", region: Region.NorthAmerica },
  { code: "NI", name: "Nicaragua", region: Region.NorthAmerica },
  { code: "PA", name: "Panama", region: Region.NorthAmerica },
  { code: "BL", name: "Saint Barthélemy", region: Region.NorthAmerica },
  { code: "MF", name: "Saint Martin (French part)", region: Region.NorthAmerica },
  { code: "PM", name: "Saint Pierre and Miquelon", region: Region.NorthAmerica },
  { code: "VC", name: "Saint Vincent and the Grenadines", region: Region.NorthAmerica },
  { code: "SX", name: "Sint Maarten (Dutch part)", region: Region.NorthAmerica },
  { code: "TT", name: "Trinidad and Tobago", region: Region.NorthAmerica },
  { code: "TC", name: "Turks and Caicos Islands", region: Region.NorthAmerica },
  { code: "VG", name: "Virgin Islands (British)", region: Region.NorthAmerica },
  { code: "VI", name: "Virgin Islands (U.S.)", region: Region.NorthAmerica },

  // ==========================================
  // REGION 1: SOUTH AMERICA
  // ==========================================
  { code: "AR", name: "Argentina", region: Region.SouthAmerica },
  { code: "BO", name: "Bolivia", region: Region.SouthAmerica },
  { code: "BR", name: "Brazil", region: Region.SouthAmerica },
  { code: "CL", name: "Chile", region: Region.SouthAmerica },
  { code: "CO", name: "Colombia", region: Region.SouthAmerica },
  { code: "EC", name: "Ecuador", region: Region.SouthAmerica },
  { code: "FK", name: "Falkland Islands", region: Region.SouthAmerica },
  { code: "GF", name: "French Guiana", region: Region.SouthAmerica },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", region: Region.SouthAmerica },
  { code: "GY", name: "Guyana", region: Region.SouthAmerica },
  { code: "PY", name: "Paraguay", region: Region.SouthAmerica },
  { code: "PE", name: "Peru", region: Region.SouthAmerica },
  { code: "SR", name: "Suriname", region: Region.SouthAmerica },
  { code: "UY", name: "Uruguay", region: Region.SouthAmerica },
  { code: "VE", name: "Venezuela", region: Region.SouthAmerica },

  // ==========================================
  // REGION 2: EUROPE
  // ==========================================
  { code: "AX", name: "Åland Islands", region: Region.Europe },
  { code: "AL", name: "Albania", region: Region.Europe },
  { code: "AD", name: "Andorra", region: Region.Europe },
  { code: "AM", name: "Armenia", region: Region.Europe },
  { code: "AT", name: "Austria", region: Region.Europe },
  { code: "AZ", name: "Azerbaijan", region: Region.Europe },
  { code: "BY", name: "Belarus", region: Region.Europe },
  { code: "BE", name: "Belgium", region: Region.Europe },
  { code: "BA", name: "Bosnia and Herzegovina", region: Region.Europe },
  { code: "BG", name: "Bulgaria", region: Region.Europe },
  { code: "HR", name: "Croatia", region: Region.Europe },
  { code: "CY", name: "Cyprus", region: Region.Europe },
  { code: "CZ", name: "Czechia", region: Region.Europe },
  { code: "DK", name: "Denmark", region: Region.Europe },
  { code: "EE", name: "Estonia", region: Region.Europe },
  { code: "FO", name: "Faroe Islands", region: Region.Europe },
  { code: "FI", name: "Finland", region: Region.Europe },
  { code: "FR", name: "France", region: Region.Europe },
  { code: "GE", name: "Georgia", region: Region.Europe },
  { code: "DE", name: "Germany", region: Region.Europe },
  { code: "GI", name: "Gibraltar", region: Region.Europe },
  { code: "GR", name: "Greece", region: Region.Europe },
  { code: "GL", name: "Greenland", region: Region.Europe },
  { code: "HU", name: "Hungary", region: Region.Europe },
  { code: "IS", name: "Iceland", region: Region.Europe },
  { code: "IT", name: "Italy", region: Region.Europe },
  { code: "LV", name: "Latvia", region: Region.Europe },
  { code: "LI", name: "Liechtenstein", region: Region.Europe },
  { code: "LT", name: "Lithuania", region: Region.Europe },
  { code: "LU", name: "Luxembourg", region: Region.Europe },
  { code: "MK", name: "North Macedonia", region: Region.Europe },
  { code: "MT", name: "Malta", region: Region.Europe },
  { code: "MD", name: "Moldova", region: Region.Europe },
  { code: "MC", name: "Monaco", region: Region.Europe },
  { code: "ME", name: "Montenegro", region: Region.Europe },
  { code: "NL", name: "Netherlands", region: Region.Europe },
  { code: "NO", name: "Norway", region: Region.Europe },
  { code: "PL", name: "Poland", region: Region.Europe },
  { code: "PT", name: "Portugal", region: Region.Europe },
  { code: "RO", name: "Romania", region: Region.Europe },
  { code: "RU", name: "Russia", region: Region.Europe },
  { code: "SM", name: "San Marino", region: Region.Europe },
  { code: "RS", name: "Serbia", region: Region.Europe },
  { code: "SK", name: "Slovakia", region: Region.Europe },
  { code: "SI", name: "Slovenia", region: Region.Europe },
  { code: "ES", name: "Spain", region: Region.Europe },
  { code: "SJ", name: "Svalbard and Jan Mayen", region: Region.Europe },
  { code: "SE", name: "Sweden", region: Region.Europe },
  { code: "CH", name: "Switzerland", region: Region.Europe },
  { code: "TR", name: "Turkey", region: Region.Europe },
  { code: "UA", name: "Ukraine", region: Region.Europe },
  { code: "VA", name: "Holy See (Vatican City)", region: Region.Europe },

  // ==========================================
  // REGION 3: UK & IRELAND
  // ==========================================
  { code: "GB", name: "United Kingdom", region: Region.UKIreland },
  { code: "IE", name: "Ireland", region: Region.UKIreland },
  { code: "GG", name: "Guernsey", region: Region.UKIreland },
  { code: "IM", name: "Isle of Man", region: Region.UKIreland },
  { code: "JE", name: "Jersey", region: Region.UKIreland },

  // ==========================================
  // REGION 4: ASIA PACIFIC
  // ==========================================
  { code: "AF", name: "Afghanistan", region: Region.AsiaPacific },
  { code: "BD", name: "Bangladesh", region: Region.AsiaPacific },
  { code: "BT", name: "Bhutan", region: Region.AsiaPacific },
  { code: "IO", name: "British Indian Ocean Territory", region: Region.AsiaPacific },
  { code: "BN", name: "Brunei Darussalam", region: Region.AsiaPacific },
  { code: "KH", name: "Cambodia", region: Region.AsiaPacific },
  { code: "CX", name: "Christmas Island", region: Region.AsiaPacific },
  { code: "CC", name: "Cocos (Keeling) Islands", region: Region.AsiaPacific },
  { code: "IN", name: "India", region: Region.AsiaPacific },
  { code: "ID", name: "Indonesia", region: Region.AsiaPacific },
  { code: "JP", name: "Japan", region: Region.AsiaPacific },
  { code: "KZ", name: "Kazakhstan", region: Region.AsiaPacific },
  { code: "KG", name: "Kyrgyzstan", region: Region.AsiaPacific },
  { code: "LA", name: "Laos", region: Region.AsiaPacific },
  { code: "MY", name: "Malaysia", region: Region.AsiaPacific },
  { code: "MV", name: "Maldives", region: Region.AsiaPacific },
  { code: "MN", name: "Mongolia", region: Region.AsiaPacific },
  { code: "MM", name: "Myanmar", region: Region.AsiaPacific },
  { code: "NP", name: "Nepal", region: Region.AsiaPacific },
  { code: "PK", name: "Pakistan", region: Region.AsiaPacific },
  { code: "PH", name: "Philippines", region: Region.AsiaPacific },
  { code: "SG", name: "Singapore", region: Region.AsiaPacific },
  { code: "LK", name: "Sri Lanka", region: Region.AsiaPacific },
  { code: "TW", name: "Taiwan", region: Region.AsiaPacific },
  { code: "TJ", name: "Tajikistan", region: Region.AsiaPacific },
  { code: "TH", name: "Thailand", region: Region.AsiaPacific },
  { code: "TL", name: "Timor-Leste", region: Region.AsiaPacific },
  { code: "TM", name: "Turkmenistan", region: Region.AsiaPacific },
  { code: "UZ", name: "Uzbekistan", region: Region.AsiaPacific },
  { code: "VN", name: "Vietnam", region: Region.AsiaPacific },

  // ==========================================
  // REGION 5: CHINA
  // ==========================================
  { code: "CN", name: "China", region: Region.China },
  { code: "HK", name: "Hong Kong", region: Region.China },
  { code: "MO", name: "Macao", region: Region.China },

  // ==========================================
  // REGION 6: AUSTRALIA & NEW ZEALAND (OCEANIA)
  // ==========================================
  { code: "AU", name: "Australia", region: Region.AustraliaNZ },
  { code: "NZ", name: "New Zealand", region: Region.AustraliaNZ },
  { code: "AS", name: "American Samoa", region: Region.AustraliaNZ },
  { code: "CK", name: "Cook Islands", region: Region.AustraliaNZ },
  { code: "FJ", name: "Fiji", region: Region.AustraliaNZ },
  { code: "PF", name: "French Polynesia", region: Region.AustraliaNZ },
  { code: "GU", name: "Guam", region: Region.AustraliaNZ },
  { code: "HM", name: "Heard Island and McDonald Islands", region: Region.AustraliaNZ },
  { code: "KI", name: "Kiribati", region: Region.AustraliaNZ },
  { code: "MH", name: "Marshall Islands", region: Region.AustraliaNZ },
  { code: "FM", name: "Micronesia", region: Region.AustraliaNZ },
  { code: "NR", name: "Nauru", region: Region.AustraliaNZ },
  { code: "NC", name: "New Caledonia", region: Region.AustraliaNZ },
  { code: "NU", name: "Niue", region: Region.AustraliaNZ },
  { code: "NF", name: "Norfolk Island", region: Region.AustraliaNZ },
  { code: "MP", name: "Northern Mariana Islands", region: Region.AustraliaNZ },
  { code: "PW", name: "Palau", region: Region.AustraliaNZ },
  { code: "PG", name: "Papua New Guinea", region: Region.AustraliaNZ },
  { code: "PN", name: "Pitcairn", region: Region.AustraliaNZ },
  { code: "WS", name: "Samoa", region: Region.AustraliaNZ },
  { code: "SB", name: "Solomon Islands", region: Region.AustraliaNZ },
  { code: "TK", name: "Tokelau", region: Region.AustraliaNZ },
  { code: "TO", name: "Tonga", region: Region.AustraliaNZ },
  { code: "TV", name: "Tuvalu", region: Region.AustraliaNZ },
  { code: "UM", name: "United States Minor Outlying Islands", region: Region.AustraliaNZ },
  { code: "VU", name: "Vanuatu", region: Region.AustraliaNZ },
  { code: "WF", name: "Wallis and Futuna", region: Region.AustraliaNZ },

  // ==========================================
  // REGION 7: MIDDLE EAST
  // ==========================================
  { code: "BH", name: "Bahrain", region: Region.MiddleEast },
  { code: "IR", name: "Iran", region: Region.MiddleEast },
  { code: "IQ", name: "Iraq", region: Region.MiddleEast },
  { code: "IL", name: "Israel", region: Region.MiddleEast },
  { code: "JO", name: "Jordan", region: Region.MiddleEast },
  { code: "KW", name: "Kuwait", region: Region.MiddleEast },
  { code: "LB", name: "Lebanon", region: Region.MiddleEast },
  { code: "OM", name: "Oman", region: Region.MiddleEast },
  { code: "PS", name: "Palestine, State of", region: Region.MiddleEast },
  { code: "QA", name: "Qatar", region: Region.MiddleEast },
  { code: "SA", name: "Saudi Arabia", region: Region.MiddleEast },
  { code: "SY", name: "Syrian Arab Republic", region: Region.MiddleEast },
  { code: "AE", name: "United Arab Emirates", region: Region.MiddleEast },
  { code: "YE", name: "Yemen", region: Region.MiddleEast },

  // ==========================================
  // REGION 8: AFRICA
  // ==========================================
  { code: "DZ", name: "Algeria", region: Region.Africa },
  { code: "AO", name: "Angola", region: Region.Africa },
  { code: "AQ", name: "Antarctica", region: Region.Africa }, 
  { code: "BJ", name: "Benin", region: Region.Africa },
  { code: "BW", name: "Botswana", region: Region.Africa },
  { code: "BV", name: "Bouvet Island", region: Region.Africa },
  { code: "BF", name: "Burkina Faso", region: Region.Africa },
  { code: "BI", name: "Burundi", region: Region.Africa },
  { code: "CV", name: "Cabo Verde", region: Region.Africa },
  { code: "CM", name: "Cameroon", region: Region.Africa },
  { code: "CF", name: "Central African Republic", region: Region.Africa },
  { code: "TD", name: "Chad", region: Region.Africa },
  { code: "KM", name: "Comoros", region: Region.Africa },
  { code: "CD", name: "Congo, Democratic Republic of the", region: Region.Africa },
  { code: "CG", name: "Congo, Republic of", region: Region.Africa },
  { code: "CI", name: "Côte d'Ivoire", region: Region.Africa },
  { code: "DJ", name: "Djibouti", region: Region.Africa },
  { code: "EG", name: "Egypt", region: Region.Africa },
  { code: "GQ", name: "Equatorial Guinea", region: Region.Africa },
  { code: "ER", name: "Eritrea", region: Region.Africa },
  { code: "SZ", name: "Eswatini", region: Region.Africa },
  { code: "ET", name: "Ethiopia", region: Region.Africa },
  { code: "TF", name: "French Southern Territories", region: Region.Africa },
  { code: "GA", name: "Gabon", region: Region.Africa },
  { code: "GM", name: "Gambia", region: Region.Africa },
  { code: "GH", name: "Ghana", region: Region.Africa },
  { code: "GN", name: "Guinea", region: Region.Africa },
  { code: "GW", name: "Guinea-Bissau", region: Region.Africa },
  { code: "KE", name: "Kenya", region: Region.Africa },
  { code: "LS", name: "Lesotho", region: Region.Africa },
  { code: "LR", name: "Liberia", region: Region.Africa },
  { code: "LY", name: "Libya", region: Region.Africa },
  { code: "MG", name: "Madagascar", region: Region.Africa },
  { code: "MW", name: "Malawi", region: Region.Africa },
  { code: "ML", name: "Mali", region: Region.Africa },
  { code: "MR", name: "Mauritania", region: Region.Africa },
  { code: "MU", name: "Mauritius", region: Region.Africa },
  { code: "YT", name: "Mayotte", region: Region.Africa },
  { code: "MA", name: "Morocco", region: Region.Africa },
  { code: "MZ", name: "Mozambique", region: Region.Africa },
  { code: "NA", name: "Namibia", region: Region.Africa },
  { code: "NE", name: "Niger", region: Region.Africa },
  { code: "NG", name: "Nigeria", region: Region.Africa },
  { code: "RE", name: "Réunion", region: Region.Africa },
  { code: "RW", name: "Rwanda", region: Region.Africa },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", region: Region.Africa },
  { code: "ST", name: "São Tomé and Príncipe", region: Region.Africa },
  { code: "SN", name: "Senegal", region: Region.Africa },
  { code: "SC", name: "Seychelles", region: Region.Africa },
  { code: "SL", name: "Sierra Leone", region: Region.Africa },
  { code: "SO", name: "Somalia", region: Region.Africa },
  { code: "ZA", name: "South Africa", region: Region.Africa },
  { code: "SS", name: "South Sudan", region: Region.Africa },
  { code: "SD", name: "Sudan", region: Region.Africa },
  { code: "TZ", name: "Tanzania", region: Region.Africa },
  { code: "TG", name: "Togo", region: Region.Africa },
  { code: "TN", name: "Tunisia", region: Region.Africa },
  { code: "UG", name: "Uganda", region: Region.Africa },
  { code: "EH", name: "Western Sahara", region: Region.Africa },
  { code: "ZM", name: "Zambia", region: Region.Africa },
  { code: "ZW", name: "Zimbabwe", region: Region.Africa }
];